version: '2'

services:

  mysql:
    image: registry.cn-qingdao.aliyuncs.com/herui-public/mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_INITDB_SKIP_TZINFO=true
      - MYSQL_HOSTNAME=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=notify
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
    ports:
      - 3306:3306
    volumes:
      - /tmp/data/notify/mysql:/var/lib/mysql

  redis:
    image: registry.cn-qingdao.aliyuncs.com/herui-public/redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - /tmp/data/notify/redis:/data

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_QUEUE=default
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672

  zookeeper:
      image: wurstmeister/zookeeper
      container_name: zookeeper
      restart: always
      ports:
          - 2181:2181

  kafka:
      image: wurstmeister/kafka
      container_name: kafka
      restart: always
      environment:
          KAFKA_ADVERTISED_HOST_NAME: kafka    #添加host
          KAFKA_CREATE_TOPICS: "default:1:1"
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ports:
          - 9092:9092

  kafka-ui:
      image: cheon/kafka-eagle:latest
      container_name: kafka-ui
      restart: always
      ports:
          - 8048:8048  #localhost:8048/ke   admin/123456
      environment:
          ZKSERVER: "zookeeper:2181"
      depends_on:
          - kafka
#
#    etcd:
#        image: bitnami/etcd
#        container_name: etcd
#        restart: always
#        ports:
#            - 2379:2379
#        environment:
#            - ALLOW_NONE_AUTHENTICATION=yes

